---
name: Kitana
version: dev
slug: ahs
description: A responsive Plex plugin web frontend
url: https://github.com/barisozdag/addon-kitana
arch:
  - aarch64
  - amd64
  - armv7
map:
  - ssl
ingress: true
panel_icon: "mdi:progress-download"
ports:
  31337/tcp: null
ports_description:
  31337/tcp: Web interface
hassio_api: true
# webui: http://[HOST]:[PORT:31337]
